@startuml

hide empty members

package structure {
    class Structure2D {
        - Mesh2D mesh
        - Material material
        - LoadCollection2D loads 
    }
}

package axis {
    class Axis2D
}

package load {
    abstract class Load2D
    class LoadCollection2D {
        + vector<Load2D *> loads
    }
    class ConcentratedLoad2D extends Load2D
}

package constraint {
    class ConstraintCollection2D {
    }
    class Constraint2D {
        - Axis2D axis
    }
}

package solver {
    class GlobalStiffnessMatrix2D {
        - SparseMatrix matrix
    }
    class ForceVector2D {

    }
}

package geometry {
    abstract class Geometry {
    }
    class Rectangle extends Geometry {
    }
}

package mesh {
    abstract class Mesh {
    }
    class Mesh2D extends Mesh {
        - vector<FiniteElements *> elements
        + GlobalStiffnessMatrix2D KMatrix()
    }
    abstract class MeshFactory {
        + Mesh CreateMesh()
    }
    class RectangleTriangulation extends MeshFactory {
        + RectangleTriangulation(Rectangle rectangle, int num_x, int num_y)
        + Mesh CreateMesh()
    }
}

package element {
    abstract class FiniteElement2D {
        + MatrixXd BMatrix()
        + MatrixXd KMatrix()
    }
    class TriangleElement2D extends FiniteElement2D
}

package material {
    class Material {
        - YoungsModulus youngs_modulus
        - PoissonsRatio poissons_ratio
        + MatrixXd DMatrix(ProblemType problem_type)
    }
    class PoissonsRatio
    class YoungsModulus
}

package node {
    abstract class Node {
    }
    class Node2D extends Node {
        - double x
        - double y
        + int Index(int i)
    }
}

package problem_type {
    enum ProblemType {
        PlainStress
        PlainStrain
    }
}

ConstraintCollection2D o-- Constraint2D : aggregation
ConstraintCollection2D <-- ForceVector2D
ConstraintCollection2D <-- GlobalStiffnessMatrix2D 
Constraint2D <-- Axis2D
Constraint2D <-- ForceVector2D
Constraint2D <-- GlobalStiffnessMatrix2D
Constraint2D <-- Node2D
Structure2D <-- Mesh2D : contains >
Structure2D <-- Material : contains >
Structure2D <-- ConstraintCollection2D : contains >
LoadCollection2D o-- Load2D : aggregation
Structure2D <-- LoadCollection2D : contains >
Mesh <-- MeshFactory : < create
Mesh2D <-- GlobalStiffnessMatrix2D
Mesh2D <-- FiniteElement2D : contains >
Rectangle <-- RectangleTriangulation : < use
FiniteElement2D <-- Node2D : contains >
TriangleElement2D <-- Node2D : contains >
Material <-- PoissonsRatio : contains >
Material <-- YoungsModulus : contains >
Material <-- ProblemType
ConcentratedLoad2D <-- Node2D

@enduml
